### PR TITLE
Update cddlp.c

### PR DESCRIPTION
**Pull request by kliem**
Proposed by komeif: determination of redundant rows

This should fix issue #45.

### CODE REVIEW

**Review by dimpase — COMMENTED** [review]
Do we have a test for this change here, or only in Sage?

**Comment by dimpase** [comment]
maybe this should also get a test - see #45.
(the testing is not set up atm, but just a file with .ine extension containing the example there and a comment
that it's to test that #45 is fixed)

**Review by dimpase — APPROVED** [review]
OK, great, thanks.

**Comment by kliem** [comment]
Ok. I tried.

**Comment by saraedum** [comment]
Perfect.

**Pull request merged**
