### PR TITLE
updated arch:ppc64le

### PR DESCRIPTION
**Pull request by genisysram**
Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by saraedum** [comment]
Thanks.

**Comment by dimpase** [comment]
I guess it's quite safe to merge, it's just adding more targets for CI.

**Comment by saraedum** [comment]
I recall that I said thanks and pressed merge. That apparently did not work :)

**Comment by saraedum** [comment]
Thanks for the ping @dimpase.

**Pull request merged**
