### PR TITLE
Add cdd/ prefix for headers

### PR DESCRIPTION
**Pull request by jengelh**
Merely installing to /usr/include/cdd does not address name clashes;
the name ought to also appear in #include statements.

Fixes: #26.

### CODE REVIEW

**Comment by saraedum** [comment]
So, should it be `cdd` or `cddlib`? Where does Debian install these to?

**Comment by jengelh** [comment]
They presently put them into `/usr/include/cdd`, but keeping them there would also mean that the `#include <setoper.h>` line, which from hereon we want to consider illegal, would still silently work (considering that most third party programs have -I/usr/include/cdd that is also considered "no longer desirable" as per this PR).
Yeah, the subject of the commit is wrong..

**Comment by saraedum** [comment]
So, if we used `usr/include/cdd` and also set our include statements to be `#include <cdd/setoper.h>`, then everything that used to work on Debian and such would still work, right? But people who run into conflicts with `#include <setoper.h>` could upgrade to `#include <cdd/setoper.h>`.

So, I do not understand why we would want to break existing code. Wouldn't the most common reaction to us installing to `/usr/include/cddlib` be that people change their gcc commands to use `-I/usr/include/cddlib` instead of `-I/usr/include/cdd` which is definitely not what we would like to see?

**Comment by saraedum** [comment]
Closing this one due to inactivity. I like the general idea but things should go into cdd/ and not into cddlib/.

**Comment by mkoeppe** [comment]
The patch that is on here was just fine. Whether to use cdd or cddlib, up to you. Users should use <cdd[lib]/setoper.h> etc. Packages that decide to upgrade to the newest upstream may have to make changes. That's OK.

**Comment by mkoeppe** [comment]
Actually the inter-header includes should be `#include "setoper.h"` (to include from the same directory). The includes from executables should be `#include <cddlib/setoper.h>`.
I'll prepare a patch.

**Comment by saraedum** [comment]
I agree that most of the patch looks good. I closed it because the original author does not seem to work on it and you'd have to create a new PR anyway. :)

**Comment by saraedum** [comment]
It should be `cdd/` for legacy reasons. Morally `cddlib` would be better but since Debian/Ubuntu already uses `cdd/` we should go for that one.

**Pull request closed without merging**
